output_dir = "/scratch/midway3/jshe/molecular-attention-bias/"

[model_config]
model_type = "BiasedAttentionTransformer"
n_tokens = 6
out_features = 3
E = 64
H = 8
D = 8
radial_function_type = "FixedPowerLaw"
dropout = 0.1
p = -1

[train_config]
epochs = 96
batch_size = 64
learning_rate = 0.001
weight_decay = 0.00001

[train_dataset_config]
dataset_type = "PointCloudDataset"
atoms_file = "/scratch/midway3/jshe/data/qm9/scaffolded/train/atoms.npy"
coordinates_file = "/scratch/midway3/jshe/data/qm9/scaffolded/train/coordinates.npy"
y_file = "/scratch/midway3/jshe/data/qm9/scaffolded/train/y.npy"
y_labels_file = "/scratch/midway3/jshe/data/qm9/transformed/y_labels.npy"
y_mean_file = "/scratch/midway3/jshe/data/qm9/transformed/y_mean.npy"
y_std_file = "/scratch/midway3/jshe/data/qm9/transformed/y_std.npy"
target_labels = ['homo', 'lumo', 'U']

[val_dataset_config]
dataset_type = "PointCloudDataset"
atoms_file = "/scratch/midway3/jshe/data/qm9/scaffolded/validation/atoms.npy"
coordinates_file = "/scratch/midway3/jshe/data/qm9/scaffolded/validation/coordinates.npy"
y_file = "/scratch/midway3/jshe/data/qm9/scaffolded/validation/y.npy"
y_labels_file = "/scratch/midway3/jshe/data/qm9/transformed/y_labels.npy"
y_mean_file = "/scratch/midway3/jshe/data/qm9/transformed/y_mean.npy"
y_std_file = "/scratch/midway3/jshe/data/qm9/transformed/y_std.npy"
target_labels = ['homo', 'lumo', 'U']